server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/users/**
            - id: product-service
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/products/**
            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/orders/**
            - id: notification-service
              uri: lb://NOTIFICATION-SERVICE
              predicates:
                - Path=/notifications/**
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: "http://localhost:4200"
                allowedMethods: [GET, POST, PUT, PATCH, DELETE, OPTIONS]
                allowedHeaders: [Authorization, Content-Type]
                maxAge: 3600

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: ${JWT_SECRET}

springdoc:
  swagger-ui:
    urls:
      - name: user-service
        url: /user-service/v3/api-docs
      - name: product-service
        url: /product-service/v3/api-docs
      - name: order-service
        url: /order-service/v3/api-docs
      - name: notification-service
        url: /notification-service/v3/api-docs